FROM pack-it-forms-dashboard-webapp
MAINTAINER Keith Amidon <camalot@picnicpark.org>
LABEL version=0.0.5
COPY dashboard /usr/local/bin/dashboard
ENTRYPOINT ["/usr/local/bin/dashboard"]
CMD []
EXPOSE 3000
