Default: &defaults
  database: pack-it-forms-dashboard.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: pack-it-forms-dashboard_test.sqlite3
  <<: *defaults

Staging:
  database: pack-it-forms-dashboard_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: pack-it-forms-dashboard_production.sqlite3
  poolsize: 100
  <<: *defaults
